//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proy_BibliotecaWeb.ServiciosEjemplares {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiciosEjemplares.EjemplaresSoap")]
    public interface EjemplaresSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperarEjemplares", ReplyAction="*")]
        void RecuperarEjemplares();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperarEjemplares", ReplyAction="*")]
        System.Threading.Tasks.Task RecuperarEjemplaresAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EjemplaresSoapChannel : Proy_BibliotecaWeb.ServiciosEjemplares.EjemplaresSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EjemplaresSoapClient : System.ServiceModel.ClientBase<Proy_BibliotecaWeb.ServiciosEjemplares.EjemplaresSoap>, Proy_BibliotecaWeb.ServiciosEjemplares.EjemplaresSoap {
        
        public EjemplaresSoapClient() {
        }
        
        public EjemplaresSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EjemplaresSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EjemplaresSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EjemplaresSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RecuperarEjemplares() {
            base.Channel.RecuperarEjemplares();
        }
        
        public System.Threading.Tasks.Task RecuperarEjemplaresAsync() {
            return base.Channel.RecuperarEjemplaresAsync();
        }
    }
}
