//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proy_BibliotecaWeb.ServiciosPrestamos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiciosPrestamos.PrestamosSoap")]
    public interface PrestamosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CargarPrestamos", ReplyAction="*")]
        void CargarPrestamos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CargarPrestamos", ReplyAction="*")]
        System.Threading.Tasks.Task CargarPrestamosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PrestamosSoapChannel : Proy_BibliotecaWeb.ServiciosPrestamos.PrestamosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrestamosSoapClient : System.ServiceModel.ClientBase<Proy_BibliotecaWeb.ServiciosPrestamos.PrestamosSoap>, Proy_BibliotecaWeb.ServiciosPrestamos.PrestamosSoap {
        
        public PrestamosSoapClient() {
        }
        
        public PrestamosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrestamosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrestamosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrestamosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CargarPrestamos() {
            base.Channel.CargarPrestamos();
        }
        
        public System.Threading.Tasks.Task CargarPrestamosAsync() {
            return base.Channel.CargarPrestamosAsync();
        }
    }
}
